name: Debug

on: [push]

env:
  BUILD_TYPE: Release

jobs:
  linux_gcc:
    if: "!contains(github.event.head_commit.message, 'ci skip') && !contains(github.event.head_commit.message, 'skip ci')"
    runs-on: ubuntu-latest
#    runs-on: ${{ matrix.os }}

    env:
      GITHUB_TARGET_OS: linux

#    strategy:
#      matrix:
#        os: [ubuntu-latest]

    steps:
    - uses: actions/checkout@v2

    - name: Install dependencies
      run: sudo apt-get update && sudo apt-get install -y cmake build-essential libogg-dev libvorbis-dev libopenal-dev libboost-all-dev libsdl2-dev libsdl2-image-dev libfreetype6-dev libraqm-dev libcurl4-openssl-dev libglew-dev libharfbuzz-dev libfribidi-dev

    - name: Checkout submodules
      run: git submodule update --init --recursive

    - name: Create Build Environment
      run: mkdir ${{runner.workspace}}/supertux/build

    - name: Configure CMake
      shell: bash
      working-directory: ${{runner.workspace}}/supertux/build
      # TODO: add -DGLBINDING_ENABLED=$USE_GLBINDING
      run: cmake $GITHUB_WORKSPACE -DCMAKE_BUILD_TYPE=$BUILD_TYPE -DWARNINGS=ON -DWERROR=ON -DBUILD_TESTS=ON -DCMAKE_INSTALL_MESSAGE=NEVER -DCMAKE_INSTALL_PREFIX=/usr -DINSTALL_SUBDIR_BIN=bin -DINSTALL_SUBDIR_SHARE=share/supertux2

    - name: Build
      shell: bash
      working-directory: ${{runner.workspace}}/supertux/build
      run: make VERBOSE=1

    - name: Try install
      shell: bash
      working-directory: ${{runner.workspace}}/supertux/build
      run: make install DESTDIR="/tmp/supertux-$BUILD_TYPE" VERBOSE=1

    - name: Run tests
      shell: bash
      working-directory: ${{runner.workspace}}/supertux/build
      run: ./test_supertux2

    - name: Create packages
      shell: bash
      working-directory: ${{runner.workspace}}/supertux/build
      run: ${{runner.workspace}}/supertux/.scripts/package.sh

    - name: Upload source
      uses: actions/upload-artifact@v2
      with:
        name: source
        path: ${{runner.workspace}}/supertux/build/s3-upload/*.tar.gz

    - name: Upload AppImage
      uses: actions/upload-artifact@v2
      with:
        name: linux_appimage
        path: ${{runner.workspace}}/supertux/build/s3-upload/*.AppImage

  macos_clang:
    if: "!contains(github.event.head_commit.message, 'ci skip') && !contains(github.event.head_commit.message, 'skip ci')"
    runs-on: macos-latest
#    runs-on: ${{ matrix.os }}

    env:
      GITHUB_TARGET_OS: linux

#    strategy:
#      matrix:
#        os: [macos-latest]

    steps:
    - uses: actions/checkout@v2

    - name: Install dependencies
      run: brew install cmake bash libogg libvorbis glew openal-soft sdl2 sdl2_image sdl2_ttf freetype harfbuzz curl-openssl fribidi boost

    - name: Checkout submodules
      run: git submodule update --init --recursive

    - name: Create Build Environment
      run: mkdir ${{runner.workspace}}/build

    - name: Configure CMake
      shell: bash
      working-directory: ${{runner.workspace}}/build
      run: cmake $GITHUB_WORKSPACE -DCMAKE_BUILD_TYPE=$BUILD_TYPE -DWARNINGS=ON -DWERROR=ON -DBUILD_TESTS=ON -DCMAKE_INSTALL_MESSAGE=NEVER -DCMAKE_INSTALL_PREFIX=/usr -DINSTALL_SUBDIR_BIN=bin -DINSTALL_SUBDIR_SHARE=share/supertux2

    - name: Build
      working-directory: ${{runner.workspace}}/build
      shell: bash
      run: make -j3
